output_dir: "./exp/Llama-3.2-0.3B_pretrain_fineweb"
learning_rate: 1.0e-4
lr_scheduler_type: "cosine"
warmup_ratio: 0.01
# warmup_steps: 1000
per_device_train_batch_size: 96
per_device_eval_batch_size: 96
gradient_accumulation_steps: 1
num_train_epochs: 1
logging_steps: 1
eval_steps: 100
save_steps: 100
save_total_limit: 2
max_steps: 10000
max_grad_norm: 1.0
report_to: "wandb"
seed: 42
run_name: "Llama-3.2-0.3B_pretrain_fineweb"

tokenizer_name: "meta-llama/Llama-3.2-1B"
# tokenizer_name: "facebook/MobileLLM-125M"
# tokenizer_name: "gpt2"
dataset_name: "HuggingFaceFW/fineweb"
max_length: 128
